SELECT
    A.ITEM_ID,
    A.ITEM_NAME,
    A.RARITY
FROM
    ITEM_INFO A NATURAL JOIN ITEM_TREE B
WHERE
    A.ITEM_ID NOT IN (SELECT IFNULL(PARENT_ITEM_ID, 0) FROM ITEM_TREE)
ORDER BY 
    ITEM_ID DESC;