-- 코드를 입력하세요
SELECT
    YEAR(B.SALES_DATE) AS YEAR,
    MONTH(B.SALES_DATE) AS MONTH,
    A.GENDER AS GENDER,
    COUNT(DISTINCT USER_ID) AS USERS
FROM 
    USER_INFO A NATURAL JOIN ONLINE_SALE B
WHERE
    A.GENDER IS NOT NULL
GROUP BY
    YEAR(B.SALES_DATE),
    MONTH(B.SALES_DATE),
    A.GENDER
ORDER BY
    YEAR, MONTH, GENDER ASC;

