SELECT
    A.ID,
    B.FISH_NAME,
    A.LENGTH
FROM 
    FISH_INFO A NATURAL JOIN FISH_NAME_INFO B
WHERE 
    (FISH_TYPE, LENGTH) IN 
    (SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO GROUP BY FISH_TYPE)
